### ISSUE TITLE
./bin/instance fg FAILS

### ISSUE THREAD

**Issue by hipertracker** [collective/plone.importexport#13] opened 2018-04-01 02:50 UTC
I cannot run the instance. It fails few seconds after starting.

```
uname -a
Darwin mbpr.local 17.5.0 Darwin Kernel Version 17.5.0: Tue Mar 13 20:39:15 PDT 2018; root:xnu-4570.51.1~36/RELEASE_X86_64 x86_64

./bin/instance fg

2018-04-01 03:48:29 INFO ZServer HTTP server started at Sun Apr  1 03:48:29 2018
	Hostname: 0.0.0.0
	Port: 8080
2018-04-01 03:48:32 INFO ZODB.blob (49089) Blob directory `/Users/hipertracker/work/plone.importexport/var/blobstorage` is unused and has no layout marker set. Selected `bushy` layout.
2018-04-01 03:48:32 INFO ZODB.blob (49089) Blob temporary directory '/Users/hipertracker/work/plone.importexport/var/blobstorage/tmp' does not exist. Created new directory.
/Users/hipertracker/work/plone.importexport/eggs/plone.app.blob-1.7.4-py2.7.egg/plone/app/blob/content.py:23: DeprecationWarning: MimeTypeException is deprecated. Import from Products.MimetypesRegistry.interfaces instead
  from Products.MimetypesRegistry.common import MimeTypeException
/Users/hipertracker/work/plone.importexport/eggs/plone.app.dexterity-2.4.8-py2.7.egg/plone/app/dexterity/__init__.py:14: DeprecationWarning: Name clash, now use '_' as usual. Will be removed in Plone 5.2
  DeprecationWarning)
/Users/hipertracker/work/plone.importexport/eggs/plone.app.multilingual-5.1.4-py2.7.egg/plone/app/multilingual/browser/migrator.py:6: DeprecationWarning: LanguageRootFolder: LanguageRootFolders should be migrate to DexterityContainers
  from plone.app.multilingual.content.lrf import LanguageRootFolder
/Users/hipertracker/work/plone.importexport/eggs/plone.portlet.collection-3.3.0-py2.7.egg/plone/portlet/collection/collection.py:2: DeprecationWarning: isDefaultPage is deprecated. Import from Products.CMFPlone instead
  from plone.app.layout.navigation.defaultpage import isDefaultPage
/Users/hipertracker/work/plone.importexport/eggs/Products.CMFPlone-5.1.0.1-py2.7.egg/Products/CMFPlone/browser/syndication/views.py:17: DeprecationWarning: wrap_form is deprecated. Import from plone.z3cform.layout instead.
  from plone.app.z3cform.layout import wrap_form
Traceback (most recent call last):
  File "/Users/hipertracker/work/plone.importexport/parts/instance/bin/interpreter", line 295, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/Users/hipertracker/work/plone.importexport/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/Users/hipertracker/work/plone.importexport/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/Users/hipertracker/work/plone.importexport/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/Users/hipertracker/work/plone.importexport/eggs/AccessControl-3.0.14-py2.7-macosx-10.13-x86_64.egg/AccessControl/security.py", line 165, in protectClass
    permission = getUtility(IPermission, name=permission_id)
  File "/Users/hipertracker/work/plone.importexport/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.configuration.config.ConfigurationExecutionError: <class 'zope.interface.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'plone.app.controlpanel.Overview')
  in:
  File "/Users/hipertracker/work/plone.importexport/eggs/plone.restapi-1.4.1-py2.7.egg/plone/restapi/services/controlpanels/configure.zcml", line 5.2-11.6
    <plone:service
      method="GET"
      for="Products.CMFPlone.interfaces.IPloneSiteRoot"
      factory=".get.ControlpanelsGet"
      name="@controlpanels"
      permission="plone.app.controlpanel.Overview"
      />
```

**Comment by idgserpro** [comment] 2018-05-03 12:56
Still don't know why, but you need to add to `plone.restapi-2.0.0-py2.7.egg/plone/restapi/services/controlpanels/configure.zcml`:

```
  <include package="plone.app.controlpanel" file="permissions.zcml"/>
```

And to `plone.restapi-2.0.0-py2.7.egg/plone/restapi/services/multilingual/configure.zcml`:

```
    <include package="plone.app.multilingual" file="permissions.zcml"/>
```

Funny enough, all the [last build in plone.restapi is green](https://travis-ci.org/plone/plone.restapi/builds/371875639), so this seems to happen only when plone.restapi is a dependency of plone.importexport. Some problem with zcml order of loading?

**Comment by idgserpro** [comment] 2018-06-19 12:40
@hipertracker I just run https://github.com/collective/plone.importexport#installation and the error is gone. Can you check it?

**Comment by djay** [comment] 2018-11-12 08:02
I still get this issue

**Comment by idgserpro** [comment] 2019-03-13 12:55
@hipertracker plone/plone.restapi#526 was closed. Maybe it will solve your problem.

**Comment by ironmaniiith** [comment] 2019-06-06 16:47
Looks like the issue is resolved, @djay can we close this?

**Closed** 2019-06-13 16:08 UTC
