### ISSUE TITLE
Adding support for large file handling

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#66] opened 2019-06-28 16:17 UTC
Even in the updated export support (#54), the way export files is done is to have a complete zip file built in memory and then sent in the response. This is a problem in case we have large files that needs to be exported, which may eventually crash up the server running the main website as well. This needs to fixed by adding a support where we can serve the files by streaming them.

**Comment by djay** [comment] 2020-12-10 13:44
duplicate of #16

**Closed by djay** 2020-12-10 13:44 UTC
